# Setup
title:               Chia Power
tagline:             'Chia energy consumption index'
description:         'Storage power consumption model to estimate the energy usage of the Chia blockchain'
url:                 https://chiapower.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jonmichael Hands
  url:               https://twitter.com/lebanonjon
  email:             Team@chiadecentral.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:             1.0
#google_analytics_id: #UA-XXXX-Y

#Google analytics stream
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z9SR3NERTV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Z9SR3NERTV');
</script>
