# Setup
title:               Chia Power
tagline:             'Chia energy consumption index'
description:         'Storage power consumption model to estimate the energy usage of the Chia blockchain'
url:                 https://chiapower.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jonmichael Hands
  url:               https://twitter.com/lebanonjon
  email:             Team@chiadecentral.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.5
google_analytics_id: #UA-XXXX-Y
