name: Build and Deploy
on:
  schedule:
    - cron: "0 2 * * *" # https://crontab.guru/#0_2_*_*_*
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run deploy
        env:
          CI: true
          NETSPACE_API_URL: ${{ secrets.NETSPACE_API_URL }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
